name: Deploy EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy-ec2-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.7

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy EC2 instance
        run: terraform apply -auto-approve

      - name: Run script on EC2
        run: |
          ssh -i ${{ secrets.YOUR_PEM_KEY_SECRET }} ec2-user@your-ec2-instance-ip 'bash -s' << 'ENDSSH'
            # Switch to the root user
            sudo su -

            # Update the package manager with automatic "yes" responses
            yes | apt update

            # Install expect with automatic "yes" responses
            yes | apt-get install -y expect

            # Download XAMPP installer
            wget https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/8.1.17/xampp-linux-x64-8.1.17-0-installer.run

            # Make the installer executable
            chmod +x xampp-linux-x64-8.1.17-0-installer.run

            yes | ./xampp-linux-x64-8.1.17-0-installer.run

            # Install netstat
            yes | apt-get install -y net-tools

            # Update the XAMPP configuration to allow access
            sed -i 's/local/all granted/' /opt/lampp/etc/extra/httpd-xampp.conf

            # Restart XAMPP
            /opt/lampp/lampp restart

            # Change to the XAMPP htdocs directory
            cd /opt/lampp/htdocs

      - name: Copy files to EC2
        run: |
          scp -i ${{ secrets.YOUR_PEM_KEY_SECRET }} -r ./* ec2-user@your-ec2-instance-ip:/opt/lampp/htdocs
