  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-2"
      - name: Setup ARM64 EC2
        id: ec2-arm64
        uses: truemark/aws-ec2-run-instance-action@v5
        with:
          security-group-id: "sg-05a30e50ae1b6e15b"
          subnet-id: "subnet-0fa7a277e0f5bc1a7"
          image-id: "default-arm64"
          instance-type: "t2.micro"
          region: "us-east-1"
          user-data: |
            #!/bin/bash
            echo "Do something cool here"
