name: Check AWS Credentials

on:
  push:
    branches:
      - main

jobs:
  check-aws-credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check AWS credentials
        run: |
          aws s3 ls
          if [ $? -eq 0 ]; then
            echo "AWS credentials are authorized."
          else
            echo "AWS credentials are NOT authorized."
            exit 1
          fi

